[package]
name = "quicktrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = { version = "6.0.0" }
fltk = { version = "1.4.14", features = ["fltk-bundled"] }
